CREATE DATABASE ONG;

CREATE TABLE RESPONSAVEL(
    CPF VARCHAR(11) PRIMARY KEY,
    Nome VARCHAR(255) NOT NULL,
    Endereco VARCHAR(255),
    renda int,
	Num_Telefone int
);

CREATE TABLE CRIANÇA(
    CPF_do_Responsavel VARCHAR(11) NOT NULL,
    Nome VARCHAR(255) NOT NULL,
    Peso FLOAT NOT NULL,
    Idade INT NOT NULL,
	Altura FLOAT NOT NULL,
	Sexo VARCHAR(3) NOT NULL,
	PRIMARY KEY(Nome,CPF_do_Responsavel)
);

CREATE TABLE MEDICO(
    CRM VARCHAR(255) NOT NULL,
    Nome VARCHAR(255) NOT NULL,
    Especialidade VARCHAR(255) NOT NULL,
    NUM_Telefone INT NOT NULL,
	PRIMARY KEY(CRM)
);

SELECT * FROM MEDICO;